- hosts: localhost 
  tasks:
  
   - name: Ensure boto and boto3 modules are installed
    pip:
      name: "{{ item }}"
    with_items:
      - boto3
      - botocore
    delegate_to: "{{ localhost }}"
    - name: Lms_Admin ec2
      cloudformation:
        stack_name: 'JenkinsToAWSDeploy'
        state: present
        region: us-east-1
        disable_rollback: true
        template_url: https://s3.amazonaws.com/vladimirvancea/Temp.yml
        template_parameters:
          KeyName: ubuntuKey
          VPCSelection: Default
